//Exercise #1

#Mulesoft Reconnection Attempts

When a Mule app starts, a connectivity test runs on components, such as the **HTTP** or **FTP** connector. These need to connect to an external server and if the test fails, the default behavior is to log a warning message and continue with the deployment of the app--instead of blocking the deployment.

You can modify this behavior by: 
1. **Fail Deployment**: Setting a number of reconnection attempts to a fixed number, and deployment fails
2. **Reconnect Forever**: Setting a number of reconnection attempts, or allowing for infinite attempts

## Fail Deployment
* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails, and any configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. 

For example, you might set a count of 5 reconnection attempts at a `frequency` of every _`4000` milliseconds (ms)_. The deployment defaults to 2 reconnection attempts at a frequency of _`2000ms`._

######Example of Fail Deployment after 5 reconnection attempts are exhausted:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

## Reconnect Forever 
* Reconnect Forever(reconnect-forever): Attempts to reconnect at a given interval, for example: every _4000 ms_ for as long as the app runs. The deployment defaults to a frequency of every _2000 ms_ since there is no limit on the number of retries, and no value for count is specified.

######Example of Reconnecting Forever with no limit:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection>
      <reconnect-forever frequency="4000" />
    </reconnection>
  </http:request-connection>
</http:request-config>
----
